services:
  api:
    build: .
    container_name: form-api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    container_name: form-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: formdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
